---
- name: installing tomcat
  hosts: all
  become: yes
  tasks:
    - name: update cache
      apt:
        state: present
        update_cache: yes
      when: ansible_facts['distribution']=='Ubuntu'
    - name: Installing jdk-11
      ansible.builtin.package:
        name: "{{ java_package_name }}"
        state: present
    - name: Creating tomcat group
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: Adding tomcat user
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home: yes
        home: "{{ user_home }}"
        group: "{{ group_name }}"
        shell: "{{ user_shell }}"
        state: present
    - name: get tomcat stats
      stat:
        path: "{{ user_home }}/latest/bin/startup.sh"
      register: tomcat_tar
    - name: Untar tomcat
      unarchive:
        src: "https://www-eu.apache.org/dist/tomcat/tomcat-{{ major_tomcat_version }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        remote_src: yes
        dest: "{{ user_home }}"
      when: not tomcat_tar.stat.exists
    - name: Finding shell files
      find:
        paths: "/opt/tomcat/apache-tomcat-{{ tomcat_version }}/bin/"
        file_type: file
        patterns: "*.sh"
        recurse: yes
      register: shell_files
    - name: Changing shell file permission
      file:
        path: "{{ item.path }}"
        state: file
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        mode: +x
      with_items:
        - "{{ shell_files }}" 
    - name: Creating symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-{{ tomcat_version }}
        dest: /opt/tomcat/latest
        state: link
      when: not tomcat_tar.stat.exists
    - name: Changing tomcat ownership
      ansible.builtin.file:
        path: /opt/tomcat
        recurse: yes
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
        state: directory
      when: not tomcat_tar.stat.exists
    - name: Creating a tomcat.service with script
      ansible.builtin.template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
      notify: Reloading daemon and start tomcat
      when: 
        - not tomcat_tar.stat.exists
    - name: User access
      ansible.builtin.template:
        src: tomcat-users.xml.j2
        dest: /opt/tomcat/latest/conf/tomcat-users.xml
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
    - name: Creating context file
      ansible.builtin.copy:
        src: context.xml 
        dest: "{{ item }}"
        owner: "{{ user_name }}"
        group: "{{ group_name }}"
      loop:
        - /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        - /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
      notify: Restart tomcat
  handlers:
    - name: Reloading daemon and start tomcat
      ansible.builtin.systemd:
        name: "{{ tomcat_service_name }}"
        daemon_reload: yes
        state: started
    - name: Restart tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        state: restarted

